language: ruby
rvm:
  - 1.9.3
addons:
  apt:
    packages:
    - xsltproc
before_install:
  - sudo mkdir -p /usr/local/etc/xml/catalog && git clone git://github.com/yob/onix-dtd.git /usr/local/etc/xml/catalog/onix && export XML_CATALOG_FILES="/usr/local/etc/xml/catalog/onix/catalog.xml $XML_CATALOG_FILES"
script: bundle exec rspec
