language: ruby
rvm:
  - 1.9.3
addons:
  apt:
    packages:
    - xsltproc
before_install:
  - cd $HOME && git clone git://github.com/yob/onix-dtd.git && export XML_CATALOG_FILES="$HOME/onix-dtd/catalog.xml $XML_CATALOG_FILES"
script: bundle exec rspec
